# Generated by Django 4.2.1 on 2023-05-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_recipe_ingredients_remove_recipe_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='units',
            new_name='unit',
        ),
    ]
