# Generated by Django 4.2.1 on 2023-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_time_recipe_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IngredientRecipe',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
